download_url: "https://drive.google.com/uc?id=1rdaAAQqsz8vePMLd8iETgdk-35Twsc72"
download_source: "drive.google"

ntr: 20000
batch_size: 256

modes: 64
visch: 1
hch: 64
pch: 64
xdim: 2
t_scaling: 1000

lengthscale: 0.001
var: 1.0
sigma_min: 0.0001

lr: 0.0001

nepoch: 10
evalint: 2
saveint: 10
generate: true
spath: "../results/"
