name: diffusion
pre_train_processor:
  _target_: training.paradigms.diffusion.DiffusionDataProcessor
  device: cuda
  vp: true
  sigma_min: 1e-4
  append_coords: ${conditioning.append_coords}
  domain_bounds: ${conditioning.domain_bounds}
  film_params: ${conditioning.film_params}
  param_keys: ${conditioning.param_keys}
