name: fm
pre_train_processor:
  _target_: training.paradigms.fm.FMDataProcessor
  device: cuda
  bridge: true
  noise_prior: gaussian
  kernel_length: 0.001
  kernel_variance: 1.0
  vp: false
  sigma_min: 1e-4
  append_coords: ${conditioning.append_coords}
  domain_bounds: ${conditioning.domain_bounds}
  film_params: ${conditioning.film_params}
  param_keys: ${conditioning.param_keys}
