_target_: models.lno.LFNO

name: lno

modes: 16
vis_channels: 1
hidden_channels: 64
x_dim: 2
t_scaling: 1
coord_channels: 0
film_param_dim: ${conditioning.param_dim}

disco_layers: true

disco_kernel_shape: [5, 5]

default_in_shape: [64, 64]

