_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 50
            "2":
                - 1
                - 50
            "3":
                - 1
                - 2
                - 16
                - 55
            "4": 3.13.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
data:
    value: '{''root_dir'': ''./data/'', ''filename'': ''fno_ns_Re20_N5000_T50.npy'', ''n_tr'': 4000, ''n_te'': 1000, ''batch_size'': 256}'
evaluation:
    value: '{''n_steps'': 50, ''device'': ''cuda:0'', ''eval_path'': ''./tasks/NS-FNO/evaluation''}'
model:
    value: '{''modes'': 64, ''visch'': 1, ''hch'': 64, ''pch'': 64, ''xdim'': 2, ''t_scaling'': 1000, ''input_dim'': 2, ''hidden_dim'': 64, ''lengthscale'': 0.001, ''var'': 1.0, ''sigma_min'': 0.0001, ''device'': ''cuda:0''}'
train:
    value: '{''lr'': 0.0001, ''epochs'': 2, ''eval_int'': 15, ''save_int'': 30, ''scheduler_step_size'': 25, ''scheduler_gamma'': 0.5, ''generate'': True, ''save_path'': ''./tasks/NS-FNO/results/'', ''checkpoint_dir'': ''./tasks/NS-FNO/checkpoints''}'
wandb:
    value: '{''project'': ''FFM-FNO'', ''model'': ''FNO'', ''entity'': ''hathreyap-university-of-stuttgart'', ''enabled'': True, ''dir'': ''./wandb-logs/FNO''}'
