defaults:
  - _self_
  - task: fno-ns
  - data: navier_stokes
  - model: fno
  - train: debug
  - eval: base
  - wandb: disabled
  - override hydra/launcher: submitit_slurm

hydra:
  run:
    dir: runs/${task.name}-${now:%Y-%m-%d_%H-%M-%S}
