defaults:
  - _self_
  - data: navier_stokes
  - model: fno
  - trainer: debug
  - wandb: disabled

experiment_name: trial

hydra:
  run:
    dir: training_runs/${model.name}-${data.name}-${experiment_name}
  sweep:
    dir: training_runs/${model.name}-${data.name}-${experiment_name}