
data:
  root_dit: data

ntr: 20000
batch_size: 256

task_name: "FFM - Navier Stokes"
task_model: "FFM-FNO"

modes: 64
visch: 1
hch: 64
pch: 64
xdim: 2
t_scaling: 1000

lengthscale: 0.001
var: 1.0
sigma_min: 0.0001

lr: 0.0001

nepoch: 10
evalint: 2
saveint: 10

generate: true
spath: "./results/"
checkpoint_dir: "./checkpoints"
